name: Build node app

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     - uses: listendev/action@v0.9
       with:
         jwt: ${{ secrets.LSTN_API_KEY }}
         ci: "only"
         argus_version: "v0.0"
         lstn: "v0.14.0"
         
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: 18

     - name: Install dependencies
       run: npm install
