name: Install pypi

on:
  pull_request:
    branches: [ "main" ]

jobs:
  install_python_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - uses: listendev/action@v0.10
        with:
          jwt: ${{ secrets.LSTN_API_KEY_DEMOS }}
          ci: only
          
      - name: Install packages
        run: pip install puffioner131
