name: Install pypi

on:
  pull_request:
    branches: [ "main" ]

jobs:
  install_python_package:
    runs-on: ubuntu-latest

    steps:

      - uses: listendev/action@v0.9
        with:
          jwt: ${{ secrets.LSTN_API_KEY }}
          ci: "only"
          argus_version: "v0.0"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Zlibxjson
        run: pip install Zlibxjson